### ISSUE TITLE
CUDA 3D texture size limit

### ISSUE THREAD

**Issue by moosmann** [astra-toolbox/astra-toolbox#157]
Issue #24 is not solved in my case. I'm using ASTRA version 1.8.3 and when running sample script 's020_3d_multiGPU' with more than 4096 projections in python or MATLAB it crashes with the same error message as in #24:
```
Error: CUDA error 11: invalid argument.
Error: Failed to allocate 1024x4097x257 GPU array
Error: CUDA error 11: invalid argument.
python: ./../../cuda/3d/util3d.cu:381: bool astraCUDA3d::transferProjectionsToArray(cudaPitchedPtr, cudaArray*, const astraCUDA3d::SDimensions3D&): Assertion err == cudaSuccess' failed.
```

**Comment by 5ht2** [comment]
What is the model of your GPU? Note that 1024x4097x257 array is ~4GB, so your card might simply not have enough memory.

**Comment by moosmann** [comment]
Definitely not. Same problem occurs if I use e.g. a 100^3 volume,, 100^2 pixels but 4097 angles. The same problem was reported before where it is related to the CUDA texture size limit when using 3D geometries. GPU model: 2 x K40 with 12 GB each

**Comment by 5ht2** [comment]
Oh, I see. Weird then - 's020_3d_multiGPU.m' sample seems to work for me with 5000 projection angles. Did you build ASTRA from source or used binaries?

**Comment by wjp** [comment]
I think I see the missing case in the code where we fail to handle more than 4k angles. I'll try to have a potential fix to test this week.

**Comment by wjp** [comment]
This should now be fixed by 0a72d3f5c67f417199dd41af373ef0e129780838 in master.

**Comment by wjp** [comment]
Incidentally, it seems my GTX1070 reports a larger max texture size (16384), so that may explain the inconsistent results.

**Comment by moosmann** [comment]
Sorry for the late feedback, but I did not receive any notifications.
The problem is solved when using `BP3D_CUDA` or `FB3D_CUDA`. However, when using `SIRT3D_CUDA` I still get the same error:

`Error: CUDA error 11: invalid argument.
Error: Failed to allocate 192x4097x128 GPU array
Error: CUDA error 11: invalid argument.
MATLAB: ./../../cuda/3d/util3d.cu:383: bool astraCUDA3d::transferProjectionsToArray(cudaPitchedPtr, cudaArray*, const astraCUDA3d::SDimensions3D&): Assertion err == cudaSuccess failed.
`

Software: CUDA 9.1, latest ASTRA version, MATLAB 2017b
GPU: 2 or 4 x Quadro M6000 or 2 x K40m
